// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: instnace/v1/instance.proto

package instance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Instance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EnvironmentId int32                  `protobuf:"varint,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ApplicationId int32                  `protobuf:"varint,3,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_instnace_v1_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_instnace_v1_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_instnace_v1_instance_proto_rawDescGZIP(), []int{0}
}

func (x *Instance) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Instance) GetEnvironmentId() int32 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *Instance) GetApplicationId() int32 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *Instance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResponsePagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponsePagination) Reset() {
	*x = ResponsePagination{}
	mi := &file_instnace_v1_instance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponsePagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePagination) ProtoMessage() {}

func (x *ResponsePagination) ProtoReflect() protoreflect.Message {
	mi := &file_instnace_v1_instance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePagination.ProtoReflect.Descriptor instead.
func (*ResponsePagination) Descriptor() ([]byte, []int) {
	return file_instnace_v1_instance_proto_rawDescGZIP(), []int{1}
}

func (x *ResponsePagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int32                  `protobuf:"varint,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ApplicationId int32                  `protobuf:"varint,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_instnace_v1_instance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instnace_v1_instance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_instnace_v1_instance_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetEnvironmentId() int32 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *CreateRequest) GetApplicationId() int32 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_instnace_v1_instance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_instnace_v1_instance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_instnace_v1_instance_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_instnace_v1_instance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instnace_v1_instance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_instnace_v1_instance_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*Instance            `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	Pagination    *ResponsePagination    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_instnace_v1_instance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_instnace_v1_instance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_instnace_v1_instance_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *ListResponse) GetPagination() *ResponsePagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_instnace_v1_instance_proto protoreflect.FileDescriptor

const file_instnace_v1_instance_proto_rawDesc = "" +
	"\n" +
	"\x1ainstnace/v1/instance.proto\x12\vinstance.v1\"|\n" +
	"\bInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12%\n" +
	"\x0eenvironment_id\x18\x02 \x01(\x05R\renvironmentId\x12%\n" +
	"\x0eapplication_id\x18\x03 \x01(\x05R\rapplicationId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"*\n" +
	"\x12ResponsePagination\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\"q\n" +
	"\rCreateRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\x05R\renvironmentId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\x05R\rapplicationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\" \n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"!\n" +
	"\vListRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x84\x01\n" +
	"\fListResponse\x123\n" +
	"\tinstances\x18\x01 \x03(\v2\x15.instance.v1.InstanceR\tinstances\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.instance.v1.ResponsePaginationR\n" +
	"pagination2\x91\x01\n" +
	"\x0fInstanceService\x12A\n" +
	"\x06Create\x12\x1a.instance.v1.CreateRequest\x1a\x1b.instance.v1.CreateResponse\x12;\n" +
	"\x04List\x12\x18.instance.v1.ListRequest\x1a\x19.instance.v1.ListResponseB\xa7\x01\n" +
	"\x0fcom.instance.v1B\rInstanceProtoP\x01Z8github.com/theleeeo/overseer/api-go/instance/v1;instance\xa2\x02\x03IXX\xaa\x02\vInstance.V1\xca\x02\vInstance\\V1\xe2\x02\x17Instance\\V1\\GPBMetadata\xea\x02\fInstance::V1b\x06proto3"

var (
	file_instnace_v1_instance_proto_rawDescOnce sync.Once
	file_instnace_v1_instance_proto_rawDescData []byte
)

func file_instnace_v1_instance_proto_rawDescGZIP() []byte {
	file_instnace_v1_instance_proto_rawDescOnce.Do(func() {
		file_instnace_v1_instance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_instnace_v1_instance_proto_rawDesc), len(file_instnace_v1_instance_proto_rawDesc)))
	})
	return file_instnace_v1_instance_proto_rawDescData
}

var file_instnace_v1_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_instnace_v1_instance_proto_goTypes = []any{
	(*Instance)(nil),           // 0: instance.v1.Instance
	(*ResponsePagination)(nil), // 1: instance.v1.ResponsePagination
	(*CreateRequest)(nil),      // 2: instance.v1.CreateRequest
	(*CreateResponse)(nil),     // 3: instance.v1.CreateResponse
	(*ListRequest)(nil),        // 4: instance.v1.ListRequest
	(*ListResponse)(nil),       // 5: instance.v1.ListResponse
}
var file_instnace_v1_instance_proto_depIdxs = []int32{
	0, // 0: instance.v1.ListResponse.instances:type_name -> instance.v1.Instance
	1, // 1: instance.v1.ListResponse.pagination:type_name -> instance.v1.ResponsePagination
	2, // 2: instance.v1.InstanceService.Create:input_type -> instance.v1.CreateRequest
	4, // 3: instance.v1.InstanceService.List:input_type -> instance.v1.ListRequest
	3, // 4: instance.v1.InstanceService.Create:output_type -> instance.v1.CreateResponse
	5, // 5: instance.v1.InstanceService.List:output_type -> instance.v1.ListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_instnace_v1_instance_proto_init() }
func file_instnace_v1_instance_proto_init() {
	if File_instnace_v1_instance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_instnace_v1_instance_proto_rawDesc), len(file_instnace_v1_instance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_instnace_v1_instance_proto_goTypes,
		DependencyIndexes: file_instnace_v1_instance_proto_depIdxs,
		MessageInfos:      file_instnace_v1_instance_proto_msgTypes,
	}.Build()
	File_instnace_v1_instance_proto = out.File
	file_instnace_v1_instance_proto_goTypes = nil
	file_instnace_v1_instance_proto_depIdxs = nil
}
