// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: environment/v1/environment.proto

package environment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_environment_v1_environment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{0}
}

func (x *Environment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Environment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Environment) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ResponsePagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponsePagination) Reset() {
	*x = ResponsePagination{}
	mi := &file_environment_v1_environment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponsePagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePagination) ProtoMessage() {}

func (x *ResponsePagination) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePagination.ProtoReflect.Descriptor instead.
func (*ResponsePagination) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{1}
}

func (x *ResponsePagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_environment_v1_environment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_environment_v1_environment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_environment_v1_environment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{4}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environments  []*Environment         `protobuf:"bytes,1,rep,name=environments,proto3" json:"environments,omitempty"`
	Pagination    *ResponsePagination    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_environment_v1_environment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetEnvironments() []*Environment {
	if x != nil {
		return x.Environments
	}
	return nil
}

func (x *ListResponse) GetPagination() *ResponsePagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_environment_v1_environment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_environment_v1_environment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{7}
}

type SetSortOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdsInOrder    []int32                `protobuf:"varint,1,rep,packed,name=ids_in_order,json=idsInOrder,proto3" json:"ids_in_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSortOrderRequest) Reset() {
	*x = SetSortOrderRequest{}
	mi := &file_environment_v1_environment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSortOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSortOrderRequest) ProtoMessage() {}

func (x *SetSortOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSortOrderRequest.ProtoReflect.Descriptor instead.
func (*SetSortOrderRequest) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{8}
}

func (x *SetSortOrderRequest) GetIdsInOrder() []int32 {
	if x != nil {
		return x.IdsInOrder
	}
	return nil
}

type SetSortOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSortOrderResponse) Reset() {
	*x = SetSortOrderResponse{}
	mi := &file_environment_v1_environment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSortOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSortOrderResponse) ProtoMessage() {}

func (x *SetSortOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSortOrderResponse.ProtoReflect.Descriptor instead.
func (*SetSortOrderResponse) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{9}
}

var File_environment_v1_environment_proto protoreflect.FileDescriptor

const file_environment_v1_environment_proto_rawDesc = "" +
	"\n" +
	" environment/v1/environment.proto\x12\x0eenvironment.v1\"P\n" +
	"\vEnvironment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\"*\n" +
	"\x12ResponsePagination\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\"#\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\" \n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\r\n" +
	"\vListRequest\"\x93\x01\n" +
	"\fListResponse\x12?\n" +
	"\fenvironments\x18\x01 \x03(\v2\x1b.environment.v1.EnvironmentR\fenvironments\x12B\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\".environment.v1.ResponsePaginationR\n" +
	"pagination\"A\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"\x10\n" +
	"\x0eUpdateResponse\"7\n" +
	"\x13SetSortOrderRequest\x12 \n" +
	"\fids_in_order\x18\x01 \x03(\x05R\n" +
	"idsInOrder\"\x16\n" +
	"\x14SetSortOrderResponse2\xc4\x02\n" +
	"\x12EnvironmentService\x12G\n" +
	"\x06Create\x12\x1d.environment.v1.CreateRequest\x1a\x1e.environment.v1.CreateResponse\x12A\n" +
	"\x04List\x12\x1b.environment.v1.ListRequest\x1a\x1c.environment.v1.ListResponse\x12G\n" +
	"\x06Update\x12\x1d.environment.v1.UpdateRequest\x1a\x1e.environment.v1.UpdateResponse\x12Y\n" +
	"\fSetSortOrder\x12#.environment.v1.SetSortOrderRequest\x1a$.environment.v1.SetSortOrderResponseB\xbf\x01\n" +
	"\x12com.environment.v1B\x10EnvironmentProtoP\x01Z>github.com/theleeeo/overseer/api-go/environment/v1;environment\xa2\x02\x03EXX\xaa\x02\x0eEnvironment.V1\xca\x02\x0eEnvironment\\V1\xe2\x02\x1aEnvironment\\V1\\GPBMetadata\xea\x02\x0fEnvironment::V1b\x06proto3"

var (
	file_environment_v1_environment_proto_rawDescOnce sync.Once
	file_environment_v1_environment_proto_rawDescData []byte
)

func file_environment_v1_environment_proto_rawDescGZIP() []byte {
	file_environment_v1_environment_proto_rawDescOnce.Do(func() {
		file_environment_v1_environment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_environment_v1_environment_proto_rawDesc), len(file_environment_v1_environment_proto_rawDesc)))
	})
	return file_environment_v1_environment_proto_rawDescData
}

var file_environment_v1_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_environment_v1_environment_proto_goTypes = []any{
	(*Environment)(nil),          // 0: environment.v1.Environment
	(*ResponsePagination)(nil),   // 1: environment.v1.ResponsePagination
	(*CreateRequest)(nil),        // 2: environment.v1.CreateRequest
	(*CreateResponse)(nil),       // 3: environment.v1.CreateResponse
	(*ListRequest)(nil),          // 4: environment.v1.ListRequest
	(*ListResponse)(nil),         // 5: environment.v1.ListResponse
	(*UpdateRequest)(nil),        // 6: environment.v1.UpdateRequest
	(*UpdateResponse)(nil),       // 7: environment.v1.UpdateResponse
	(*SetSortOrderRequest)(nil),  // 8: environment.v1.SetSortOrderRequest
	(*SetSortOrderResponse)(nil), // 9: environment.v1.SetSortOrderResponse
}
var file_environment_v1_environment_proto_depIdxs = []int32{
	0, // 0: environment.v1.ListResponse.environments:type_name -> environment.v1.Environment
	1, // 1: environment.v1.ListResponse.pagination:type_name -> environment.v1.ResponsePagination
	2, // 2: environment.v1.EnvironmentService.Create:input_type -> environment.v1.CreateRequest
	4, // 3: environment.v1.EnvironmentService.List:input_type -> environment.v1.ListRequest
	6, // 4: environment.v1.EnvironmentService.Update:input_type -> environment.v1.UpdateRequest
	8, // 5: environment.v1.EnvironmentService.SetSortOrder:input_type -> environment.v1.SetSortOrderRequest
	3, // 6: environment.v1.EnvironmentService.Create:output_type -> environment.v1.CreateResponse
	5, // 7: environment.v1.EnvironmentService.List:output_type -> environment.v1.ListResponse
	7, // 8: environment.v1.EnvironmentService.Update:output_type -> environment.v1.UpdateResponse
	9, // 9: environment.v1.EnvironmentService.SetSortOrder:output_type -> environment.v1.SetSortOrderResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_environment_v1_environment_proto_init() }
func file_environment_v1_environment_proto_init() {
	if File_environment_v1_environment_proto != nil {
		return
	}
	file_environment_v1_environment_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_environment_v1_environment_proto_rawDesc), len(file_environment_v1_environment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_environment_v1_environment_proto_goTypes,
		DependencyIndexes: file_environment_v1_environment_proto_depIdxs,
		MessageInfos:      file_environment_v1_environment_proto_msgTypes,
	}.Build()
	File_environment_v1_environment_proto = out.File
	file_environment_v1_environment_proto_goTypes = nil
	file_environment_v1_environment_proto_depIdxs = nil
}
