// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDeployments = `-- name: ListDeployments :many
SELECT
  instance_id,
  version,
  deployed_at
FROM deployments
`

type ListDeploymentsRow struct {
	InstanceID int32              `json:"instance_id"`
	Version    string             `json:"version"`
	DeployedAt pgtype.Timestamptz `json:"deployed_at"`
}

func (q *Queries) ListDeployments(ctx context.Context) ([]ListDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, listDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeploymentsRow
	for rows.Next() {
		var i ListDeploymentsRow
		if err := rows.Scan(&i.InstanceID, &i.Version, &i.DeployedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerDeployment = `-- name: RegisterDeployment :exec
INSERT INTO deployments (id, instance_id, version, deployed_at)
VALUES ($1, $2, $3, $4)
`

type RegisterDeploymentParams struct {
	ID         pgtype.UUID        `json:"id"`
	InstanceID int32              `json:"instance_id"`
	Version    string             `json:"version"`
	DeployedAt pgtype.Timestamptz `json:"deployed_at"`
}

// Register a deployment
func (q *Queries) RegisterDeployment(ctx context.Context, arg RegisterDeploymentParams) error {
	_, err := q.db.Exec(ctx, registerDeployment,
		arg.ID,
		arg.InstanceID,
		arg.Version,
		arg.DeployedAt,
	)
	return err
}
