// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	SortOrder int32  `json:"sort_order"`
}

type Deployment struct {
	ID         pgtype.UUID        `json:"id"`
	InstanceID int32              `json:"instance_id"`
	Version    string             `json:"version"`
	DeployedAt pgtype.Timestamptz `json:"deployed_at"`
}

type Environment struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	SortOrder int32  `json:"sort_order"`
}

type Instance struct {
	ID            int32  `json:"id"`
	Name          string `json:"name"`
	EnvironmentID int32  `json:"environment_id"`
	ApplicationID int32  `json:"application_id"`
}
