// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: deployment/v1/deployment.proto

package deployment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int32                  `protobuf:"varint,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ApplicationId int32                  `protobuf:"varint,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	DeployedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_deployment_v1_deployment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_deployment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_deployment_v1_deployment_proto_rawDescGZIP(), []int{0}
}

func (x *Deployment) GetEnvironmentId() int32 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *Deployment) GetApplicationId() int32 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *Deployment) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Deployment) GetDeployedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeployedAt
	}
	return nil
}

type ResponsePagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponsePagination) Reset() {
	*x = ResponsePagination{}
	mi := &file_deployment_v1_deployment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponsePagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePagination) ProtoMessage() {}

func (x *ResponsePagination) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_deployment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePagination.ProtoReflect.Descriptor instead.
func (*ResponsePagination) Descriptor() ([]byte, []int) {
	return file_deployment_v1_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *ResponsePagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int32                  `protobuf:"varint,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ApplicationId int32                  `protobuf:"varint,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	DeployedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_deployment_v1_deployment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_deployment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_deployment_v1_deployment_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetEnvironmentId() int32 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *RegisterRequest) GetApplicationId() int32 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetDeployedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeployedAt
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_deployment_v1_deployment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_deployment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_deployment_v1_deployment_proto_rawDescGZIP(), []int{3}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_deployment_v1_deployment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_deployment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_deployment_v1_deployment_proto_rawDescGZIP(), []int{4}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*Deployment          `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	Pagination    *ResponsePagination    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_deployment_v1_deployment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_deployment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_deployment_v1_deployment_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *ListResponse) GetPagination() *ResponsePagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_deployment_v1_deployment_proto protoreflect.FileDescriptor

const file_deployment_v1_deployment_proto_rawDesc = "" +
	"\n" +
	"\x1edeployment/v1/deployment.proto\x12\rdeployment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x01\n" +
	"\n" +
	"Deployment\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\x05R\renvironmentId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\x05R\rapplicationId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12;\n" +
	"\vdeployed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deployedAt\"*\n" +
	"\x12ResponsePagination\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\"\xb6\x01\n" +
	"\x0fRegisterRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\x05R\renvironmentId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\x05R\rapplicationId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12;\n" +
	"\vdeployed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deployedAt\"\x12\n" +
	"\x10RegisterResponse\"\r\n" +
	"\vListRequest\"\x8e\x01\n" +
	"\fListResponse\x12;\n" +
	"\vdeployments\x18\x01 \x03(\v2\x19.deployment.v1.DeploymentR\vdeployments\x12A\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2!.deployment.v1.ResponsePaginationR\n" +
	"pagination2\xa1\x01\n" +
	"\x11DeploymentService\x12K\n" +
	"\bRegister\x12\x1e.deployment.v1.RegisterRequest\x1a\x1f.deployment.v1.RegisterResponse\x12?\n" +
	"\x04List\x12\x1a.deployment.v1.ListRequest\x1a\x1b.deployment.v1.ListResponseB\xb7\x01\n" +
	"\x11com.deployment.v1B\x0fDeploymentProtoP\x01Z<github.com/theleeeo/overseer/api-go/deployment/v1;deployment\xa2\x02\x03DXX\xaa\x02\rDeployment.V1\xca\x02\rDeployment\\V1\xe2\x02\x19Deployment\\V1\\GPBMetadata\xea\x02\x0eDeployment::V1b\x06proto3"

var (
	file_deployment_v1_deployment_proto_rawDescOnce sync.Once
	file_deployment_v1_deployment_proto_rawDescData []byte
)

func file_deployment_v1_deployment_proto_rawDescGZIP() []byte {
	file_deployment_v1_deployment_proto_rawDescOnce.Do(func() {
		file_deployment_v1_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deployment_v1_deployment_proto_rawDesc), len(file_deployment_v1_deployment_proto_rawDesc)))
	})
	return file_deployment_v1_deployment_proto_rawDescData
}

var file_deployment_v1_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_deployment_v1_deployment_proto_goTypes = []any{
	(*Deployment)(nil),            // 0: deployment.v1.Deployment
	(*ResponsePagination)(nil),    // 1: deployment.v1.ResponsePagination
	(*RegisterRequest)(nil),       // 2: deployment.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 3: deployment.v1.RegisterResponse
	(*ListRequest)(nil),           // 4: deployment.v1.ListRequest
	(*ListResponse)(nil),          // 5: deployment.v1.ListResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_deployment_v1_deployment_proto_depIdxs = []int32{
	6, // 0: deployment.v1.Deployment.deployed_at:type_name -> google.protobuf.Timestamp
	6, // 1: deployment.v1.RegisterRequest.deployed_at:type_name -> google.protobuf.Timestamp
	0, // 2: deployment.v1.ListResponse.deployments:type_name -> deployment.v1.Deployment
	1, // 3: deployment.v1.ListResponse.pagination:type_name -> deployment.v1.ResponsePagination
	2, // 4: deployment.v1.DeploymentService.Register:input_type -> deployment.v1.RegisterRequest
	4, // 5: deployment.v1.DeploymentService.List:input_type -> deployment.v1.ListRequest
	3, // 6: deployment.v1.DeploymentService.Register:output_type -> deployment.v1.RegisterResponse
	5, // 7: deployment.v1.DeploymentService.List:output_type -> deployment.v1.ListResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_deployment_v1_deployment_proto_init() }
func file_deployment_v1_deployment_proto_init() {
	if File_deployment_v1_deployment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployment_v1_deployment_proto_rawDesc), len(file_deployment_v1_deployment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deployment_v1_deployment_proto_goTypes,
		DependencyIndexes: file_deployment_v1_deployment_proto_depIdxs,
		MessageInfos:      file_deployment_v1_deployment_proto_msgTypes,
	}.Build()
	File_deployment_v1_deployment_proto = out.File
	file_deployment_v1_deployment_proto_goTypes = nil
	file_deployment_v1_deployment_proto_depIdxs = nil
}
